language: c
compiler:
  - clang
  - gcc
install:
  - sudo apt-get update
  - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y libwnck-dev libxklavier-dev libgtk2.0-dev dh-autoreconf libappindicator-dev dh-make devscripts fakeroot
  - ./autogen.sh
script:
  - echo "Testing Debian package build"
  - dpkg-buildpackage -us -uc -rfakeroot -b

